/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
    './src/shared/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#48dead',
        'surface-container-low': '#f2f4f6',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#000767',
        'surface-variant': '#e0e3e5',
        background: '#ffffff',
        'secondary-fixed-dim': '#bdc2ff',
        'on-surface-variant': '#3c4a43',
        'on-background': '#191c1e',
        'surface-container': '#eceef0',
        'on-tertiary-fixed': '#410002',
        'on-primary-container': '#004431',
        'surface-tint': '#006c4f',
        tertiary: '#a33c34',
        'inverse-surface': '#2d3133',
        secondary: '#4c56af',
        'surface-container-highest': '#e0e3e5',
        'primary-fixed': '#6afbc8',
        'surface-container-lowest': '#ffffff',
        primary: '#006c4f',
        'on-primary-fixed': '#002116',
        'on-surface': '#191c1e',
        'secondary-container': '#959efd',
        'tertiary-container': '#fe8074',
        surface: '#ffffff',
        'on-tertiary-container': '#731815',
        'surface-dim': '#d8dadc',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'surface-bright': '#ffffff',
        error: '#ba1a1a',
        'on-secondary-container': '#27308a',
        'primary-container': '#01bc8d',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#343d96',
        outline: '#6c7a73',
        'on-tertiary-fixed-variant': '#83241f',
        'tertiary-fixed-dim': '#ffb4ab',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#48dead',
        'secondary-fixed': '#e0e0ff',
        'inverse-on-surface': '#eff1f3',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#00513b',
        'tertiary-fixed': '#ffdad6',
        'outline-variant': '#bbcac1',
        'surface-container-high': '#e6e8ea',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
